/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tftpserver;

import tftpserver.db.Db;
import tftpserver.db.InMemDb;
import tftpserver.db.MongoDb;
import tftpserver.handlers.RequestHandler;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;

public class App {

    public static void main(String[] args) {
        // Instantiate the DB
        InMemDb.getDb();

        try (DatagramSocket tftpSocket = new DatagramSocket(69)) {

            // Lets create a sufficiently big buffer because the
            // request packets have filenames which can be really big
            int bufLength = 1024;
            byte[] requestPacketBuffer = new byte[bufLength];

            DatagramPacket requestPacket = new DatagramPacket(requestPacketBuffer, bufLength);

            // Wait to get a request
            // TODO Lets assume it's always a SET request for now.
            // TODO (For Vidit) Implement strategy to check if req. is SET or GET
            tftpSocket.receive(requestPacket);
            Runnable requestHandler = new RequestHandler(requestPacket);
            requestHandler.run();

        } catch (IOException e) {
            e.printStackTrace();
            System.exit(-1);
        }
    }
}
